//Settings Service list api
export const SETTING_SERVICE_PENDING = 'SETTING_SERVICE_PENDING'
export const SETTING_SERVICE_ERROR = 'SETTING_SERVICE_ERROR'
export const SETTING_SERVICE_SUCCESS = 'SETTING_SERVICE_SUCCESS'

//Home Service list api
export const HOME_SERVICE_PENDING = 'HOME_SERVICE_PENDING'
export const HOME_SERVICE_ERROR = 'HOME_SERVICE_ERROR'
export const HOME_SERVICE_SUCCESS = 'HOME_SERVICE_SUCCESS'

//Home Payment list api
export const PAYMENT_LIST_PENDING = 'PAYMENT_LIST_PENDING'
export const PAYMENT_LIST_ERROR = 'PAYMENT_LIST_ERROR'
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS'

export const STRIPE_PENDING = 'STRIPE_PENDING'
export const STRIPE_ERROR = 'STRIPE_ERROR'
export const STRIPE_SUCCESS = 'STRIPE_SUCCESS'

//Faq list api
export const FAQ_LIST_PENDING = 'FAQ_LIST_PENDING'
export const FAQ_LIST_ERROR = 'FAQ_LIST_ERROR'
export const FAQ_LIST_SUCCESS = 'FAQ_LIST_SUCCESS'

//Product list api
export const PRODUCT_LIST_PENDING = 'PRODUCT_LIST_PENDING'
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const PRODUCT_RESET = 'PRODUCT_RESET'
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET'

//Register api
export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

//Register api
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

//Address api
export const CREATE_ADDRESS_PENDING = 'CREATE_ADDRESS_PENDING'
export const CREATE_ADDRESS_ERROR = 'CREATE_ADDRESS_ERROR'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'

export const EDIT_ADDRESS_PENDING = 'EDIT_ADDRESS_PENDING'
export const EDIT_ADDRESS_ERROR = 'EDIT_ADDRESS_ERROR'
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS'

export const UPDATE_ADDRESS_PENDING = 'UPDATE_ADDRESS_PENDING'
export const UPDATE_ADDRESS_ERROR = 'UPDATE_ADDRESS_ERROR'
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'

//Address list api
export const ADDRESS_LIST_PENDING = 'ADDRESS_LIST_PENDING'
export const ADDRESS_LIST_ERROR = 'ADDRESS_LIST_ERROR'
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS'

export const ADDRESS_DELETE_PENDING = 'ADDRESS_LIST_PENDING'
export const ADDRESS_DELETE_ERROR = 'ADDRESS_LIST_ERROR'
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_LIST_SUCCESS'

//Cart api
export const SUB_TOTAL = 'SUB_TOTAL'
export const TOTAL = 'TOTAL'
export const PROMO = 'PROMO'
export const CALCULATE_PRICING = 'CALCULATE_PRICING'
export const SELECT_ADDRESS = 'SELECT_ADDRESS'
export const SELECT_DATE = 'SELECT_DATE'
export const RESET = 'RESET'

//MyOrders api
export const MYORDERS_LIST_PENDING = 'MYORDERS_LIST_PENDING'
export const MYORDERS_LIST_ERROR = 'MYORDERS_LIST_ERROR'
export const MYORDERS_LIST_SUCCESS = 'MYORDERS_LIST_SUCCESS'
export const FILTER_TYPE = 'FILTER_TYPE'

//Promo Code api
export const PROMO_LIST_PENDING = 'PROMO_LIST_PENDING'
export const PROMO_LIST_ERROR = 'PROMO_LIST_ERROR'
export const PROMO_LIST_SUCCESS = 'PROMO_LIST_SUCCESS'

//Profile api
export const EDIT_PROFILE_PENDING = 'EDIT_PROFILE_PENDING'
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'

//Forgot Service list api
export const FORGOT_SERVICE_PENDING = 'FORGOT_SERVICE_PENDING'
export const FORGOT_SERVICE_ERROR = 'FORGOT_SERVICE_ERROR'
export const FORGOT_SERVICE_SUCCESS = 'FORGOT_SERVICE_SUCCESS'

//Otp Service list api
export const OTP_SERVICE_PENDING = 'OTP_SERVICE_PENDING'
export const OTP_SERVICE_ERROR = 'OTP_SERVICE_ERROR'
export const OTP_SERVICE_SUCCESS = 'OTP_SERVICE_SUCCESS'

//Reset Service list api
export const RESET_SERVICE_PENDING = 'RESET_SERVICE_PENDING'
export const RESET_SERVICE_ERROR = 'RESET_SERVICE_ERROR'
export const RESET_SERVICE_SUCCESS = 'RESET_SERVICE_SUCCESS'

//Payment Actions
export const ORDER_SERVICE_PENDING = 'ORDER_SERVICE_PENDING'
export const ORDER_SERVICE_ERROR = 'ORDER_SERVICE_ERROR'
export const ORDER_SERVICE_SUCCESS = 'ORDER_SERVICE_SUCCESS'
export const TAP_STATUS = 'TAP_STATUS'

//Privacy Policy Actions
export const PRIVACY_SERVICE_PENDING = 'PRIVACY_SERVICE_PENDING'
export const PRIVACY_SERVICE_ERROR = 'PRIVACY_SERVICE_ERROR'
export const PRIVACY_SERVICE_SUCCESS = 'PRIVACY_SERVICE_SUCCESS'
